yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('logout/',
         LogoutView.as_view(template_name='users/logged_out.html'),
         name='logout'),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form'),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_comlete'),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='password_reset_confirm'),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'),
        name='password_change'),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'),
        name='password_change_done'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, unique=True,
                             verbose_name='Название')
    slug = models.SlugField(unique=True,
                            verbose_name='Slug')
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста',
                            help_text='Введите текст поста')
    pub_date = models.DateTimeField(auto_now_add=True,
                                    verbose_name='Дата публикации')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='posts',
                               verbose_name='Автор')
    group = models.ForeignKey(
        Group, blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост')

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from django import forms

from .models import Group, Post


class PostForm(forms.ModelForm):
    text = forms.CharField(
        widget=forms.Textarea,
        label='Текст поста',
        help_text='Текст нового поста')
    group = forms.ModelChoiceField(
        required=False,
        queryset=Group.objects.all(),
        label='Группа',
        help_text='Группа, к которой будет относиться пост')

    class Meta:
        model = Post
        fields = ('text', 'group',)

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.text import Truncator

from .forms import PostForm
from .models import Group, Post
from .utils import paginate_posts

User = get_user_model()


def index(request):
    """Главная страница."""
    page_obj = paginate_posts(request, Post.objects.select_related())
    context = {'page_obj': page_obj, }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Страница группы."""
    group = get_object_or_404(Group, slug=slug)
    page_obj = paginate_posts(
        request,
        group.posts.select_related('author'))
    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    page_obj = paginate_posts(request, author.posts.select_related())
    num_posts = author.posts.count()
    context = {
        'page_obj': page_obj,
        'author': author,
        'num_posts': num_posts,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    num_posts = post.author.posts.count()
    text_for_title = Truncator(post.text).chars(settings.SYMB_FOR_TITLE)
    is_author = bool(post.author == request.user)
    context = {
        'post': post,
        'num_posts': num_posts,
        'text_for_title': text_for_title,
        'is_author': is_author,
    }

    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)

    if form.is_valid():
        form_data = form.save(commit=False)
        form_data.author = request.user
        form_data.save()

        return redirect('posts:profile', request.user.username)

    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = Post.objects.get(pk=post_id)

    if post.author != request.user:
        return redirect('posts:post_detail', post_id)

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:post_detail', post_id)
    else:
        form = PostForm(instance=post)

    context = {
        'is_edit': True,
        'form': form,
        'post_id': post_id,
    }

    return render(request, 'posts/create_post.html', context)

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<div class="container py-5">
<h1>Привет, я автор</h1>
  <p>
    Тут я размещу информацию о себе, используя свои умения верстать.
    Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста. 
  </p>
</div>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row">
    <h1>Вот что я умею</h1>

    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Python
        </li>
        <li class="list-group-item">
          Django
        </li>
      </ul>
    </aside>  
    <article class="col-12 col-md-9">
      <p>Текст страницы "Технологии"</p>
    </article>
  </div>
</div>
{% endblock %}

yatube/templates/base.html
<!DOCTYPE html>
<html lang="ru">
  <head>    
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main> 
      {% block content %}
      На этой странице ничего нет        
      {% endblock %}
    </main>
    {% include 'includes/footer.html' %}    
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name == 'about:author' %}active{% endif %}" href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name == 'about:tech' %}active{% endif %}" href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"> 
          <a class="nav-link {% if view_name == 'posts:post_create' or view_name == 'posts:post_edit' %}active{% endif %}" href="{% url 'posts:post_create' %}">Новая запись</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name == 'users:password_change' %}active{% endif %}" href="{% url 'users:password_change' %}">Изменить пароль</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      {% endwith %}
      </ul>      
    </div>
  </nav>      
</header>

yatube/templates/includes/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
      {% if page_obj.has_previous %}
      <li class="page-item">
          <a class="page-link" href="?page=1">Первая</a>
      </li>
      <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
              Предыдущая
          </a>
      </li>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}
          <li class="page-item active">
              <span class="page-link">{{ i }}</span>
          </li>       
          {% else %}
          <li class="page-item">
              <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
          {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">
              Следующая
          </a>            
      </li>   
      <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
              Последняя
          </a>
      </li>
      {% endif %}
  </ul>
</nav>
{% endif %}

yatube/templates/includes/post.html
<ul>
  {% with request.resolver_match.view_name as view_name %}
  {% if view_name != 'posts:profile' %}
  <li>    
    Автор: {{ post.author.get_full_name }} 
    <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
  </li>
  {% endif %}
  <li>
    Дата публикации: {{ post.pub_date|date:"d E Y" }}
  </li>
  {% endwith %}
</ul>      
<p>{{ post.text }}</p>
{% if view_name != 'posts:profile' %}
<a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
{% endif %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
{% if is_edit %}
Редактировать пост
{% else %}
Новый пост
{% endif %}
{% endblock title %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
          Редактировать пост
          {% else %}       
          Новый пост
          {% endif %}             
        </div>
        <div class="card-body">
            {% load user_filters %}
          {% if is_edit %}
          <form method="post" action="{% url 'posts:post_edit' post_id %}">    
          {% else %}
          <form method="post" action="{% url 'posts:post_create' %}">    
          {% endif %}
            {% csrf_token %}
            {% for field in form %} 
            {% for error in field.errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
            {% endfor %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                  <span class="required text-danger">*</span>
                {% endif %}
              </label>
              {{ field|addclass:'form-control' }}
              {% if field.help_text %}
              <small 
                 id="{{ field.id_for_label }}-help"
                 class="form-text text-muted"
              >
                {{ field.help_text|safe }}
              </small>
              {% endif %}
            </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                  Сохранить
                  {% else %}
                  Добавить
                  {% endif %}
                </button>
            </div>          
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}{{ group.title }}{% endblock %}

{% block content %}
<div class="container py-5">
  <h1> {{ group.title }} </h1>
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    <article>
      {% include 'includes/post.html' %}
    </article>
    {% if post.group %}
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}    
  {% include 'includes/paginator.html' %}
</div>  
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}Последние обновления на сайте{% endblock %}

{% block content%}
<div class="container py-5">       
  {% for post in page_obj %}
  <article>
    {% include 'includes/post.html' %}    
  </article>
  {% if post.group %}
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}  
  {% include 'includes/paginator.html' %}
</div>  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %} Пост {{ text_for_title }} {% endblock %}

{% block content %}
<div class="container py-5">
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}   
          <li class="list-group-item">
            Группа: {{ post.group.title }}<br>
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>            
          </li>
        {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }} {{ post.author.username }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ num_posts }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      <p>
          {{ post.text }}
      </p>
      {% if is_author %}
      <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
        редактировать запись
      </a>              
      {% endif %}  

    </article>
  </div> 
</div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %} {{ author.get_full_name }} профайл пользователя {% endblock %}

{% block content %}
<div class="container py-5">        
  <h1>Все посты пользователя {{ author.get_full_name }} </h1>
  <h3>Всего постов: {{ num_posts }} </h3>  
  {% for post in page_obj %} 
  <article>
    {% include 'includes/post.html' %}    
  </article>
  {% if post.group %}       
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a> 
  {% endif %}
  {% if not forloop.last %}<hr>{% endif %}       
  {% endfor %}
  {% include 'includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
      <div class="col-md-8 p-5">
          <div class="card">
              <div class="card-header">
                  Выход
              </div>
              <div class="card-body">
                  <p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
              </div>
          </div>
      </div>
  </div>
</div>
{% endblock  %}

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>              
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}          
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>
{% endblock %}

yatube/templates/users/password_change_done.html
{% extends 'base.html' %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Пароль изменён
        </div>
        <div class="card-body"> 
          <p>Пароль изменён успешно</p>
        </div> 
      </div> 
    </div> 
  </div> 
</div>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Изменить пароль
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3 p-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>              
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}          
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Изменить пароль
            </button>
          </div>
          </form>
        </div> 
      </div> 
    </div> 
  </div> 
</div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Восстановление пароля завершено
        </div>
        <div class="card-body">
          <p>Ваш пароль был сохранен. Используйте его для входа</p>
          <a href="{% url 'users:login' %}">войти</a>
        </div> 
      </div> 
    </div>
  </div> 
</div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
{% load user_filters %}
{% if validlink %}
<div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Введите новый пароль
          </div>
          <div class="card-body">
            {% if form.errors %}
                {% for field in form %}
                  {% for error in field.errors %}            
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
            {% endif %}
  
            <form method="post"
              {% if action_url %}
                action="{% url action_url %}"
              {% endif %}
            >
            {% csrf_token %}
  
            {% for field in form %}
              <div class="form-group row my-3 p-3"
                {% if field.field.required %} 
                  aria-required="true"
                {% else %}
                  aria-required="false"
                {% endif %}
              >
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                </label>
                {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}                
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Назначить новый пароль
              </button>
            </div>
            </form>
          </div> 
        </div> 
      </div> 
    </div> 
  </div>
{% else %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Ошибка</div>
        <div class="card-body">
          <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
        </div> 
      </div> 
    </div> 
  </div> 
</div>
{% endif %}
{% endblock %} 

yatube/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Отправлено письмо
        </div>
        <div class="card-body">
          <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
        </div> 
      </div> 
    </div>
  </div> 
</div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} 
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

            <form method="post" action="{% url 'users:signup' %}">
             {% csrf_token %}
             {% for field in form %} 
              <div class="form-group row my-3 p-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>                  
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> 
        </div> 
      </div> 
    </div>
  </div> 
</div>
{% endblock %} 